---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      loadtester_version: "^2.x"
      dns_zone: dev.promotion.mmst.eu
      gcp_project_id: mms-gib-proco-d-0815
      gcp_analytics_project_id: mms-gib-analytics-d-1105
