---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-charts
  namespace: dashboard
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wego
  namespace: dashboard
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-charts
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      username: admin
      # password: admin
      passwordHash: $2a$10$ZGFJf47srKNbwhjGK1C/YuyH3WnyBp.6yA3dakpgqSSjSAeRxZRCq
    additionalArgs:
      - "--route-prefix=/wego"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wego-dashboard
  namespace: dashboard
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |-
      location = /wego {
        return 301 /wego/;
      }
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: wego-weave-gitops
                port:
                  number: 9001
            path: /wego
            pathType: Prefix
