---
name: Renovate
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '23 5 * * *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate
        uses: renovatebot/github-action@v39.1.3
        with:
          # GitHub personal access token with 'public_repo' scope used to create version bump pull requests
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
