---
name: Test local setup
# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: get_head_commit_message
        run: echo "headCommitMsg=$(git show -s --format=%s)" >> $GITHUB_OUTPUT

  test:
    needs: check_skip
    if: ${{ !(startsWith(needs.check_skip.outputs.head-commit-message, 'Add Flux') && endsWith(needs.check_skip.outputs.head-commit-message, 'manifests')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: podman
            NO_PODMAN: 0
            # rootless podman not supported on GH action runner because cgroup v2 is not enabled
            sudo: "sudo -E"
          - name: docker
            NO_PODMAN: 1
            sudo: ""
    name: local setup using ${{ matrix.name }}
    env:
      NO_PODMAN: ${{ matrix.NO_PODMAN }}
    steps:
      - run: echo '${{ needs.check_skip.outputs.head-commit-message }}'

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - run: ${{ matrix.sudo }} make prepare

      - run: ${{ matrix.sudo }} make pre-check

      - run: ${{ matrix.sudo }} make new

      - run: ${{ matrix.sudo }} make check

      - run: ${{ matrix.sudo }} make bootstrap
        env:
          # GitHub personal access token with full 'repo' scope used to test the flux bootstrap process
          GITHUB_TOKEN: ${{ secrets.BOOTSTRAP_TEST_TOKEN }}

      - run: ${{ matrix.sudo }} make wait

      - run: |
          curl -fs http://localhost:8080/dashboard
          curl -fsk https://localhost:8443/dashboard
          curl -fs http://localhost:8080/dashboard/#/about
          curl -fsk https://localhost:8443/dashboard/#/about

      - run: ${{ matrix.sudo }} make clean

      - run: |
          # reset flux sync target branch
          git config --global user.email "ci@acti.on"
          git config --global user.name "${{ github.actor }}"

          git pull
          git checkout origin/main -- local-cluster/flux-system/gotk-sync.yaml
          git add local-cluster/flux-system/gotk-sync.yaml
          set -e
          git commit --amend --allow-empty -m "$(git log -n 1 --oneline --format="%s")"
          if [ $? -eq 0 ]; then
            set -e
            git push --force
          else
            echo "No changes on gotk-sync.yaml"
          fi
